from __future__ import annotations

from typing import Protocol

from .models import ArtifactRecord, EdgeRecord, EventRecord, NodeRecord

class KnowledgeStore(Protocol):
    def init(self) -> None: ...
    def upsert_node(self, node: NodeRecord) -> None: ...
    def add_edge(self, edge: EdgeRecord) -> None: ...
    def add_event(self, event: EventRecord) -> None: ...
    def add_artifact(self, artifact: ArtifactRecord) -> None: ...
    def get_node(self, campaign_id: str, node_id: str) -> NodeRecord | None: ...
    def list_nodes(self, campaign_id: str, *, node_type: str | None = None, limit: int = 100) -> list[NodeRecord]: ...
    def list_edges(self, campaign_id: str, *, src_id: str | None = None, dst_id: str | None = None, edge_type: str | None = None, limit: int = 200) -> list[EdgeRecord]: ...
    def list_events(self, campaign_id: str, *, limit: int = 100) -> list[EventRecord]: ...
    def list_artifacts(self, campaign_id: str, *, artifact_type: str | None = None, limit: int = 100) -> list[ArtifactRecord]: ...
